name: "csteach422"
subname: "Software Development for Wireless and Mobile Devices"
description: "a collection of resources for cs teaching..."

url: "http://localhost:4000"

paginate: 10

markdown: kramdown
permalink: "/:categories/:title"
highlighter: rouge

excerpt_separator: <!--more-->

collections:
  library:
    output: true
  indices:
    output: true

gems:
  - jekyll-sitemap
